# Generated by Django 4.1.3 on 2023-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_infor',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('pin_code', models.CharField(blank=True, default='', max_length=10)),
                ('nation', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_events_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_comments', models.TextField()),
                ('event_date', models.DateField()),
                ('event_completed', models.BooleanField()),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('event_title', 'event_date')},
            },
        ),
    ]
