# Generated by Django 4.1.3 on 2023-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_events_info',
            name='event_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_events_info',
            name='event_description',
            field=models.TextField(blank=True),
        ),
    ]
