# Generated by Django 4.1.3 on 2023-01-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0002_alter_user_events_info_event_comments_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_events_info',
            unique_together={('event_title', 'event_date', 'username')},
        ),
    ]
