# Generated by Django 4.1.3 on 2023-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0003_alter_user_events_info_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('admin_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('pin_code', models.CharField(blank=True, default='', max_length=10)),
                ('nation', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('admin_auth_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
