# Generated by Django 4.1.3 on 2023-01-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0004_admin_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ticket_title', models.CharField(max_length=100)),
                ('ticket_description', models.TextField()),
                ('ticket_status', models.CharField(choices=[('Active', 'Active'), ('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
            ],
        ),
    ]
